AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template that deploys a sample static website to showcase
  third-party applications on Amazon Connect. This web application that you can integrate 
  with your Amazon Connect instance demostrates the agent events, agent requests, contact events and 
  contact requests that are supported by the Amazon Connect SDK. This template will host a sample webpage on 
  Amazon S3 and serve it via Amazon CloudFront. **WARNING** This template creates an Amazon S3 
  bucket and a CloudFront distribution. You will be billed for these AWS resources used 
  if you create a stack from this template.'

Resources:
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Required optional comment
  DistributionForS3:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Comment: Distribution for Website
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - S3OriginConfig:
              OriginAccessIdentity: !Sub >-
                origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
            DomainName: !Sub '${S3BucketForWebsiteContent.RegionalDomainName}'
            Id: only-origin
    DependsOn:
      - CloudFrontOriginAccessIdentity
      - S3BucketForWebsiteContent
  S3BucketForWebsiteContent:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        BucketEncryption: 
          ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3BucketForWebsiteContent'
      PolicyDocument:
        Version: '2012-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: 403Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
                ${CloudFrontOriginAccessIdentity}'
            Action: "s3:ListBucket"
            Resource: !Sub 'arn:aws:s3:::${S3BucketForWebsiteContent}'
          - Sid: ObjectAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
                ${CloudFrontOriginAccessIdentity}'
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${S3BucketForWebsiteContent}/*'
  CopyArtifactsLambdaIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:ListBucket'
                  - 's3:ListBucketVersions'
                Resource: 
                  - !Sub 'arn:aws:s3:::${S3BucketForWebsiteContent}/*'
                  - !Sub 'arn:aws:s3:::share-with-customers-external/*'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  CustomResourceCopySourceFunction:
      Type: 'AWS::Lambda::Function'
      Properties:
        Role: !GetAtt CopyArtifactsLambdaIamRole.Arn
        Handler: "index.lambda_handler"
        Runtime: "python3.8"
        Code:
          ZipFile: |
            import logging
            import urllib.request
            import io
            import cfnresponse
            from boto3 import resource

            logger = logging.getLogger()
            logger.setLevel(logging.INFO)

            def download_from_cloudfront(cloudfront_url, object_key):
                try:
                    cloudfront_url = cloudfront_url.rstrip('/')
                    url = f"{cloudfront_url}/{object_key}"
                    with urllib.request.urlopen(url) as response:
                        return response.read()
                except Exception as e:
                    logger.error(f"Error downloading {object_key} from CloudFront: {e}")
                    raise

            def upload_to_s3(s3_resource, destination_bucket, object_key, content, content_type):
                try:
                    s3_object = s3_resource.Object(destination_bucket, object_key)
                    s3_object.put(Body=content, ContentType=content_type)
                except Exception as e:
                    logger.error(f"Error uploading {object_key} to S3: {e}")
                    raise

            def get_content_type(file_extension):
                # Map file extension to content type
                content_type_mapping = {
                    'html': 'text/html',
                    'json': 'application/json',
                    'txt': 'text/plain',
                    'css': 'text/css',
                    'map': 'application/octet-stream',
                    'js': 'application/javascript',
                    'png': 'image/png',
                    'ico': 'image/x-icon',
                    # Add more extensions and corresponding content types as needed
                }

                # Default to 'application/octet-stream' if extension is not found
                return content_type_mapping.get(file_extension, 'application/octet-stream')

            def lambda_handler(event, context):
                global s3_resource
                s3_resource = resource('s3')

                try:
                    print(f"Received event with type {event['RequestType']}")

                    if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
                        source_cloudfront_url = "https://d1khg2kbc0gpyh.cloudfront.net/cloudformation"
                        destination_bucket_name = event['ResourceProperties']['S3BucketForWebsiteContent']

                        files_to_copy = [
                            "asset-manifest.json",
                            "favicon.ico",
                            "index.html",
                            "logo192.png",
                            "logo512.png",
                            "manifest.json",
                            "robots.txt",
                            "static/css/main.c950918a.css",
                            "static/css/main.c950918a.css.map",
                            "static/js/787.f9285100.chunk.js",
                            "static/js/787.f9285100.chunk.js.map",
                            "static/js/main.b42d09ba.js",
                            "static/js/main.b42d09ba.js.LICENSE.txt",
                            "static/js/main.b42d09ba.js.map",
                            "static/media/3PAppsBanner.cc0aef4b18b3a3fb2a00.png",
                            "static/.DS_Store"  # Include .DS_Store inside the static folder
                        ]

                        for object_key in files_to_copy:
                            cloudfront_content = download_from_cloudfront(source_cloudfront_url, object_key)
                            file_extension = object_key.split('.')[-1].lower()
                            content_type = get_content_type(file_extension)

                            upload_to_s3(s3_resource, destination_bucket_name, object_key, cloudfront_content, content_type)
                            print(f"Finished copying File: {object_key}")

                        cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Data': 'Successfully processed files'}, 'mainstack')
                    elif event['RequestType'] == 'Delete':
                        cfnresponse.send(event, context, cfnresponse.SUCCESS, {'Data': 'Successfully deleted files'}, 'mainstack')
                except Exception as error:
                    print(error)
                    cfnresponse.send(event, context, cfnresponse.FAILED, {'Data': 'Failed to process event'}, 'mainstack')

        Timeout: 300
      DependsOn:
      - CloudFrontOriginAccessIdentity
      - S3BucketForWebsiteContent
      - CopyArtifactsLambdaIamRole
  CopyCfnStacksLambdaTrigger:
    Type: 'Custom::CopyCfnStacksLambdaTrigger'
    DependsOn:
      - CustomResourceCopySourceFunction
      - S3BucketForWebsiteContent
      - CopyArtifactsLambdaIamRole
    Properties:
      ServiceToken: !GetAtt CustomResourceCopySourceFunction.Arn
      S3BucketForWebsiteContent: !Ref S3BucketForWebsiteContent
Outputs:
  WebsiteURL:
    Value: !GetAtt DistributionForS3.DomainName
    Description: The URL of the newly created distribution to access website
  BucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket to hold website content
